"""empty message

Revision ID: 44421236e2db
Revises: d32e0e6cd032
Create Date: 2021-01-18 11:25:23.242495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44421236e2db'
down_revision = 'd32e0e6cd032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.alter_column('question', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
