"""empty message

Revision ID: fc15f0913631
Revises: 62a8a0d96b97
Create Date: 2021-01-19 13:17:42.895235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc15f0913631'
down_revision = '62a8a0d96b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_answer_id_answer'), 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_answer_id_answer'), type_='foreignkey')
        batch_op.drop_column('question_id')
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###
